### ISSUE TITLE
Missing version `GLIBC_2.14' and `GLIBC_2.15' from deb install

### ISSUE THREAD

**Issue by jdorweiler** [rhiokim/haroopad#271]
I'm using Debian Wheezy 7.2.  The deb package for v0.10.0 throws these two errors when trying to open. 

<code>/usr/share/haroopad/haroopad: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /usr/share/haroopad/haroopad)
/usr/share/haroopad/haroopad: /lib/x86_64-linux-gnu/libc.so.6: version`GLIBC_2.15' not found (required by /usr/share/haroopad/haroopad)</code>

**Comment by rhiokim** [comment]
Hope [this](https://bbs.archlinux.org/viewtopic.php?pid=1151168) and [this](http://askubuntu.com/questions/315907/libc-so-6-version-glibc-2-16-not-found) will help you

**Comment by rhiokim** [comment]
is it ok?

**Comment by rhiokim** [comment]
And https://github.com/rogerwang/node-webkit/issues/1454

Closing until further information is provided.

**Comment by RobertinoValue** [comment]
I bumped into the same issue several times over the past 6-7 months.
Compiling on Wheezy from source fails because of this same reason. There is no official v2.14/2.15 or newer from Debian's repos either packaged or source.

I waited for either Debian to upgrade Wheezy's glibc, or Haroopad to drop the hard version dependency.

**Is Haroopad's hard dependency on glibc v2.14 and v2.15 really necessary?**

Debian Wheezy is built on glibc v2.13 (actually eglibc) from its initial release. See the screenshot below.
I can only assume that this package was created on a Debian derivative (Ubuntu, Mint, or WHY).
This is a *.deb package which fails on Debian. :(

Replacing glibc with a different version, without recompiling **everything**,  is like pulling the foundation from under parts of your OS and many packages. Everything C is compiled against it.

**EDIT: Added the screenshot.**

![2014-07-05--1404566911_1365x418_scrot](https://cloud.githubusercontent.com/assets/2570736/3486786/32f17eae-0451-11e4-9a10-d90c073fcecc.png)

**Comment by mumuxme** [comment]
I'm using debian7.6 (wheezy). It's ok when i install the 'haroopad-v0.12.0_amd64.deb' , but while i am running it takes the same error as you, however, I just change my sources list (/etc/apt/sources.list), and add a debian testing sources, then I only update the ' libc6 ' (and some dependence) to version2.19. Then all things seems well. (ps: If you don't want to change you os, you may not do this)

**Comment by rhiokim** [comment]
@RobertinoValue glibc issue is known. This problem is associated with a node-webkit. 
Because Haroopad based on the node-webkit.

Presumably you can get solution [here](https://github.com/rogerwang/node-webkit/search?q=glibc&ref=cmdform&type=Issues)

@mumu314 I like your tip. Thanks :+1:

**Comment by RobertinoValue** [comment]
@mumu314 Thanks, I know the way to install from unstable/testing, but I already wrote that replacing glibc can and will lead to issues. This Debian notebook is my main workhorse, I'm not willing and going to add an almost 100% risk at possible instability. glibc is too important/tricky to tinker with.

@rhiokim Thanks, but in that case, I prefer to wait until Debian Wheezy/7 and Haroopad/node-webkit become compatible.

I wish it was different. :(

**Comment by RobertinoValue** [comment]
There is hope : http://www.phoronix.com/scan.php?page=news_item&px=MTcyNDY
v2.19 was in experimental/new, but it's not there anymore. Also not in incoming.
But with Debian always taking donkies years to make a move ..........
BTW, just discovered that Adobe Brackets has the exact same error messages. (Sigh!) :(
