### ISSUE TITLE
error export to html

### ISSUE THREAD

**Issue by rhiokim** [rhiokim/haroopad#278]
affect version : v0.10.0
fix version : v0.10.1

**Comment by rhiokim** [comment]
because of npm module problem.

**Comment by ghost** [comment]
Looks like it's been more than 15 days. is there an ETA?

**Comment by rhiokim** [comment]
Why do not you use the Copy to Clipboard?
We are planning to release the next version after 7days (ETA)

**Comment by ghost** [comment]
Didn't even know that was possible...that's good to know.

Thanks!

**Comment by druide** [comment]
I'm also can't export from Haroopad v0.10.0 on my Windows 8.1 x64. Btw, export to clipboard doesn't do anything for me too.

**Comment by ghost** [comment]
druide // it's completely broken on v0.10.0. You can click the preview and
select the whole text then copy them and then create a file then paste the
content. The problem is that the result is not the same as an exported
HTML. That means, if you might need to re-export them once this issue is
fixed.
