### ISSUE TITLE
HiDPI support

### ISSUE THREAD

**Issue by rikai** [rhiokim/haroopad#464]
Haroopad lacks HiDPI support & therefore looks terrible and tiny on a HiDPI screen.

It'd be great to see HiDPI support added. :+1:

**Comment by rhiokim** [comment]
Haroopad v0.13.x already supports High-DPI.

based on Node-webkit v0.11.5, test screen shot - https://www.flickr.com/photos/129626304@N03/16170097405/

**Comment by spiffytech** [comment]
How can I activate HiDPI mode? It's not working for me (Haroopad 0.13.1, Debian Jessie, Cinnamon Desktop).

![haroopad-hidpi](https://cloud.githubusercontent.com/assets/77867/12875518/7fc4fb64-cdba-11e5-836c-67e40ad42949.png)

**Comment by psiho** [comment]
same here. Linux Mint Cinnamon... show stopper for me. Everything is tiny.

SOLVED:  don't know much about NW.js but it seems to be probelm on their side. Too bad this is not mentioned in docs of haroopad but you can get it displayed correctly if you start it with:

`haroopad --force-device-scale-factor=2`

... that will manually force NW.js to scale.

**Comment by alanmimms** [comment]
Sorry to say I didn't find this issue until I created a new one: #616 .

**Comment by alanmimms** [comment]
The `--force-device-scale-factor=2` solution is far from complete. The menus are way too small to hold the text they contain and the menu titles (click to show menu) are too big as well. Minor point: initial size of window is way too small.

Since Preferences window is not resizable (on KDE X11 anyway), it's way too small and effectively unusable as a result.

**Comment by DDCMI** [comment]
Same Problem, and @alanmimms is correct, the `haroopad --force-device-scale-factor=2` is not a good solution. 
OS: Ubuntu 16.04.3
Haroopad Version: 0.13.1
