### ISSUE TITLE
I set .md files to open with Haroopad on Windows. IF FILENAME CONTAINS SPACES it won't launch.

### ISSUE THREAD

**Issue by ghost** [rhiokim/haroopad#582]
**Haroopad version: 0.13.1**
**OS: Windows 7**

On Windows I set Haroopad as the default program for markdown files.
When I tried opening the file `Untitled - Code Editors.md` it won't start.
Upon renaming the file to `untitled-code-editors.md` it fixed the problem.
I tried playing with the filenames a bit and I have confirmed that **the bug is caused by spaces in the filename**.

**Comment by anti-matt-er** [comment]
I can confirm this, moreover the process starts but otherwise nothing happens. 
Same Haroopad version (0.13.1), but my OS is Windows 10.

The quick workaround is simply opening Haroopad first and then using it to open said document, which is fine if you're aware of this bug and it avoids needlessly renaming the file; but if you're not aware of it then it's rather confusing as it doesn't even throw an error, it just silently opens the process and does nothing more. For non-technical users this would be a serious issue.
